ALTER TABLE indicators ADD COLUMN IF NOT EXISTS sma9_d NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS sma9_rising_d BOOLEAN;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS sma20_d NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS sma20_rising_d BOOLEAN;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS bb_pc_d NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS bb_pc_w NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS bb_pc_m NUMERIC(10,4);

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_d NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS dmi_bull_d BOOLEAN;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_crossing_date_d DATE;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_slope_d BOOLEAN;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_w NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS dmi_bull_w BOOLEAN;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_crossing_date_w DATE;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_slope_w BOOLEAN;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_m NUMERIC(10,4);
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS dmi_bull_m BOOLEAN;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_crossing_date_m DATE;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS adx_slope_m BOOLEAN;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS psar_bull_d BOOLEAN;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS psar_change_date_d DATE;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS psar_bull_w BOOLEAN;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS psar_change_date_w DATE;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS psar_bull_m BOOLEAN;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS psar_change_date_m DATE;

ALTER TABLE indicators ADD COLUMN IF NOT EXISTS volume_sma INTEGER;
ALTER TABLE indicators ADD COLUMN IF NOT EXISTS volume_sma_slope BOOLEAN;